--- Problem 1: List the case number, type of crime and community area for all crimes in community area number 18.

SELECT CCD.CASE_NUMBER, CCD.PRIMARY_TYPE, CCD.COMMUNITY_AREA_NUMBER
FROM CHICAGO_CRIME_DATA CCD INNER JOIN CHICAGO_SOCIOECONOMIC_DATA CSD
ON CCD.COMMUNITY_AREA_NUMBER = CSD.CA
WHERE CCD.COMMUNITY_AREA_NUMBER = 18;

--- Problem 2: List all crimes that took place at a school. Include case number, crime type and community name.

SELECT CCD.CASE_NUMBER, CCD.PRIMARY_TYPE, CCD.LOCATION_DESCRIPTION, CSD.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA CCD LEFT JOIN CHICAGO_SOCIOECONOMIC_DATA CSD
ON CCD.COMMUNITY_AREA_NUMBER = CSD.CA
WHERE CCD.LOCATION_DESCRIPTION LIKE '%SCHOOL%';

--- Problem 3: For the communities of Oakland, Armour Square, Edgewater and CHICAGO list the associated community_area_numbers and the case_numbers.

SELECT CSD.COMMUNITY_AREA_NAME, CCD.COMMUNITY_AREA_NUMBER, CCD.CASE_NUMBER
FROM CHICAGO_CRIME_DATA CCD full JOIN CHICAGO_SOCIOECONOMIC_DATA CSD
ON CCD.COMMUNITY_AREA_NUMBER = CSD.CA
WHERE CSD.COMMUNITY_AREA_NAME IN ('Oakland', 'Armour Square', 'Edgewater', 'Edgewater', 'CHICAGO');
